version: "3.2"

services:
  api:
    restart: always
    container_name: node-project
    build: 
      context: ./server
    ports:
      - "4000:4000"

  react:
    restart: always
    container_name: react-project
    build:
      context: ./client/
    depends_on:
      - api
    ports:
      - "80:80"
      